extends: default
rules:
  line-length:
    max: 120
    level: error
  indentation:
    spaces: 2
  truthy:
    allowed-values: [ true, false, null ]
  trailing-spaces:
    level: error
  document-start: disable
