const Map<String, String> stringsAr = {
  // Dashboard & Navigation
  'bio_sync_active': 'Bio-Sync نشط',
  'hello_user': 'مرحبا، {name}',
  'new_suggestion_loaded': 'تم تحميل اقتراح جديد',
  'coming_soon': 'قريباً',
  'finish_setup': 'أكمل الإعداد',
  'setup_description':
      'أكمل الملف الشخصي وقواعد النظام الغذائي ومزامنة الجهاز لفتح الخطط التكيفية.',
  'continue': 'متابعة',
  'live_vitals': 'العلامات الحيوية الحية',
  'vitals_synced': 'تمت مزامنة العلامات الحيوية',
  'ai_suggestion': 'اقتراح الذكاء الاصطناعي',
  'daily_fuel': 'الطاقة اليومية',
  'quick_log': 'تسجيل سريع',
  'view_history': 'عرض السجل',
  'refresh': 'تحديث',
  'why_this': 'لماذا هذا؟',
  'eat_this': 'تناول هذا ({cals} كيلو كالوري)',
  // General
  'hello': 'مرحبا',
  'welcome': 'أهلا وسهلا',
  'logout': 'تسجيل الخروج',
  'settings': 'الإعدادات',
  'profile': 'الملف الشخصي',
  'about': 'حول',
  'version': 'الإصدار',
  'language': 'اللغة',
  'english': 'English',
  'arabic': 'العربية',
  'save': 'حفظ',
  'cancel': 'إلغاء',
  'delete': 'حذف',
  'edit': 'تعديل',
  'add': 'إضافة',
  'loading': 'جاري التحميل',
  'error': 'خطأ',
  'success': 'نجح',
  'try_again': 'حاول مرة أخرى',

  // Health & Nutrition
  'calories': 'السعرات الحرارية',
  'protein': 'البروتين',
  'carbs': 'الكربوهيدرات',
  'fat': 'الدهون',
  'water': 'الماء',
  'hydration': 'الترطيب',
  'sleep_score': 'درجة النوم',
  'heart_rate': 'ضربات القلب',
  'steps': 'الخطوات',
  'stress': 'الضغط',
  'stress_level': 'مستوى الإجهاد',

  // Meal & Food
  'meal': 'الوجبة',
  'meals': 'الوجبات',
  'breakfast': 'الإفطار',
  'lunch': 'الغداء',
  'dinner': 'العشاء',
  'snack': 'وجبة خفيفة',
  'log_meal': 'تسجيل الوجبة',
  'meal_suggestion': 'اقتراح الوجبة',
  'recipe': 'الوصفة',
  'ingredients': 'المكونات',
  'portion': 'الحصة',
  'servings': 'الحصص',

  // Analytics & Time
  'analytics': 'التحليلات',
  'today': 'اليوم',
  'week': 'هذا الأسبوع',
  'month': 'هذا الشهر',
  'year': 'هذا العام',
  'daily': 'يومي',
  'weekly': 'أسبوعي',
  'monthly': 'شهري',
  'history': 'التاريخ',
  'trend': 'الاتجاه',

  // Pantry & Planner
  'pantry': 'المخزن',
  'planner': 'المخطط',
  'shopping': 'التسوق',
  'leftover': 'بقايا الطعام',
  'cooking_mode': 'وضع الطهي',
  'eating_out': 'تناول الطعام بالخارج',
};
