const Map<String, String> stringsKo = {
  'bio_sync_inactive': 'Bio-Sync Inactive',
  // Dashboard & Navigation
  'bio_sync_active': 'Bio‑Sync 활성화',
  'hello_user': '안녕하세요, {name}',
  'new_suggestion_loaded': '새 제안이 로드되었습니다',
  'coming_soon': '곧 제공됩니다',
  'finish_setup': '설정 완료하기',
  'setup_description': '프로필, 식단 규칙 및 기기 동기화를 완료하면 적응형 플랜을 잠금 해제합니다.',
  'continue': '계속',
  'live_vitals': '실시간 생체 신호',
  'vitals_synced': '생체 신호 동기화됨',
  'ai_suggestion': 'AI 제안',
  'daily_fuel': '일일 에너지',
  'quick_log': '빠른 기록',
  'view_history': '기록 보기',
  'refresh': '새로고침',
  'why_this': '이유',
  'eat_this': '이것을 먹기 ({cals} kcal)',

  // General
  'hello': '안녕하세요',
  'welcome': '환영합니다',
  'logout': '로그아웃',
  'settings': '설정',
  'profile': '프로필',
  'about': '정보',
  'version': '버전',
  'language': '언어',
  'english': 'English',
  'arabic': 'العربية',
  'save': '저장',
  'cancel': '취소',
  'delete': '삭제',
  'edit': '편집',
  'add': '추가',
  'loading': '로딩 중',
  'error': '오류',
  'success': '성공',
  'try_again': '다시 시도',

  // Health & Nutrition
  'calories': '칼로리',
  'protein': '단백질',
  'carbs': '탄수화물',
  'fat': '지방',
  'water': '물',
  'hydration': '수분',
  'sleep_score': '수면 점수',
  'heart_rate': '심박수',
  'steps': '걸음 수',
  'stress': '스트레스',
  'stress_level': '스트레스 수준',

  // Meal & Food
  'meal': '식사',
  'meals': '식사',
  'breakfast': '아침',
  'lunch': '점심',
  'dinner': '저녁',
  'snack': '간식',
  'log_meal': '식사 기록',
  'meal_suggestion': '식사 제안',
  'recipe': '레시피',
  'ingredients': '재료',
  'portion': '1회 제공량',
  'servings': '인분',

  // Analytics & Time
  'analytics': '분석',
  'today': '오늘',
  'week': '주',
  'month': '월',
  'year': '년',
  'daily': '일별',
  'weekly': '주별',
  'monthly': '월별',
  'history': '기록',
  'trend': '추세',

  // Pantry & Planner
  'pantry': '팬트리',
  'planner': '플래너',
  'shopping': '쇼핑',
  'leftover': '남은 음식',
  'cooking_mode': '요리 모드',
  'eating_out': '외식',
};
