const Map<String, String> stringsEn = {
  // Dashboard & Navigation
  'bio_sync_active': 'Bio-Sync Active',
  'bio_sync_inactive': 'Bio-Sync Inactive',
  'hello_user': 'Hello, {name}',
  'new_suggestion_loaded': 'New suggestion loaded',
  'coming_soon': 'Coming soon',
  'finish_setup': 'Finish your setup',
  'setup_description':
      'Complete profile, dietary rules, and device sync to unlock adaptive plans.',
  'continue': 'Continue',
  'live_vitals': 'Live Vitals',
  'vitals_synced': 'Vitals synced',
  'ai_suggestion': 'AI Suggestion',
  'daily_fuel': 'Daily Fuel',
  'quick_log': 'Quick Log',
  'view_history': 'View History',
  'refresh': 'Refresh',
  'why_this': 'Why this?',
  'eat_this': 'Eat This ({cals} kcal)',

  // General
  'hello': 'Hello',
  'welcome': 'Welcome',
  'logout': 'Logout',
  'settings': 'Settings',
  'profile': 'Profile',
  'about': 'About',
  'version': 'Version',
  'language': 'Language',
  'english': 'English',
  'arabic': 'العربية',
  'save': 'Save',
  'cancel': 'Cancel',
  'delete': 'Delete',
  'edit': 'Edit',
  'add': 'Add',
  'loading': 'Loading',
  'error': 'Error',
  'success': 'Success',
  'try_again': 'Try Again',

  // Health & Nutrition
  'calories': 'Calories',
  'protein': 'Protein',
  'carbs': 'Carbs',
  'fat': 'Fat',
  'water': 'Water',
  'hydration': 'Hydration',
  'sleep_score': 'Sleep Score',
  'heart_rate': 'Heart Rate',
  'steps': 'Steps',
  'stress': 'Stress',
  'stress_level': 'Stress Level',

  // Meal & Food
  'meal': 'Meal',
  'meals': 'Meals',
  'breakfast': 'Breakfast',
  'lunch': 'Lunch',
  'dinner': 'Dinner',
  'snack': 'Snack',
  'log_meal': 'Log Meal',
  'meal_suggestion': 'Meal Suggestion',
  'recipe': 'Recipe',
  'ingredients': 'Ingredients',
  'portion': 'Portion',
  'servings': 'Servings',

  // Analytics & Time
  'analytics': 'Analytics',
  'today': 'Today',
  'week': 'Week',
  'month': 'Month',
  'year': 'Year',
  'daily': 'Daily',
  'weekly': 'Weekly',
  'monthly': 'Monthly',
  'history': 'History',
  'trend': 'Trend',

  // Pantry & Planner
  'pantry': 'Pantry',
  'planner': 'Planner',
  'shopping': 'Shopping',
  'leftover': 'Leftover',
  'cooking_mode': 'Cooking Mode',
  'eating_out': 'Eating Out',
};
