const Map<String, String> stringsFr = {
  'bio_sync_inactive': 'Bio-Sync Inactive',
  // Dashboard & Navigation
  'bio_sync_active': 'Bio‑Sync activé',
  'hello_user': 'Bonjour, {name}',
  'new_suggestion_loaded': 'Nouvelle suggestion chargée',
  'coming_soon': 'Bientôt disponible',
  'finish_setup': 'Terminez votre configuration',
  'setup_description':
      'Complétez le profil, les règles alimentaires et la synchronisation des appareils pour débloquer des plans adaptatifs.',
  'continue': 'Continuer',
  'live_vitals': 'Signes vitaux en direct',
  'vitals_synced': 'Signes vitaux synchronisés',
  'ai_suggestion': 'Suggestion IA',
  'daily_fuel': 'Apport quotidien',
  'quick_log': 'Journal rapide',
  'view_history': 'Voir l’historique',
  'refresh': 'Actualiser',
  'why_this': 'Pourquoi ceci ?',
  'eat_this': 'Mangez ceci ({cals} kcal)',

  // General
  'hello': 'Bonjour',
  'welcome': 'Bienvenue',
  'logout': 'Se déconnecter',
  'settings': 'Paramètres',
  'profile': 'Profil',
  'about': 'À propos',
  'version': 'Version',
  'language': 'Langue',
  'english': 'Anglais',
  'arabic': 'العربية',
  'save': 'Enregistrer',
  'cancel': 'Annuler',
  'delete': 'Supprimer',
  'edit': 'Modifier',
  'add': 'Ajouter',
  'loading': 'Chargement',
  'error': 'Erreur',
  'success': 'Succès',
  'try_again': 'Réessayer',

  // Health & Nutrition
  'calories': 'Calories',
  'protein': 'Protéines',
  'carbs': 'Glucides',
  'fat': 'Graisses',
  'water': 'Eau',
  'hydration': 'Hydratation',
  'sleep_score': 'Score de sommeil',
  'heart_rate': 'Fréquence cardiaque',
  'steps': 'Pas',
  'stress': 'Stress',
  'stress_level': 'Niveau de stress',

  // Meal & Food
  'meal': 'Repas',
  'meals': 'Repas',
  'breakfast': 'Petit-déjeuner',
  'lunch': 'Déjeuner',
  'dinner': 'Dîner',
  'snack': 'Collation',
  'log_meal': 'Enregistrer le repas',
  'meal_suggestion': 'Suggestion de repas',
  'recipe': 'Recette',
  'ingredients': 'Ingrédients',
  'portion': 'Portion',
  'servings': 'Portions',

  // Analytics & Time
  'analytics': 'Analytique',
  'today': 'Aujourd’hui',
  'week': 'Semaine',
  'month': 'Mois',
  'year': 'Année',
  'daily': 'Quotidien',
  'weekly': 'Hebdomadaire',
  'monthly': 'Mensuel',
  'history': 'Historique',
  'trend': 'Tendance',

  // Pantry & Planner
  'pantry': 'Garde‑manger',
  'planner': 'Planificateur',
  'shopping': 'Courses',
  'leftover': 'Restes',
  'cooking_mode': 'Mode cuisson',
  'eating_out': 'Repas à l’extérieur',
};
