const Map<String, String> stringsZh = {
  'bio_sync_inactive': 'Bio-Sync Inactive',
  // Dashboard & Navigation
  'bio_sync_active': '生物同步已启用',
  'hello_user': '你好，{name}',
  'new_suggestion_loaded': '已加载新建议',
  'coming_soon': '敬请期待',
  'finish_setup': '完成设置',
  'setup_description': '完成个人资料、饮食规则和设备同步以解锁自适应计划。',
  'continue': '继续',
  'live_vitals': '实时生命体征',
  'vitals_synced': '生命体征已同步',
  'ai_suggestion': 'AI 建议',
  'daily_fuel': '每日能量',
  'quick_log': '快速记录',
  'view_history': '查看历史',
  'refresh': '刷新',
  'why_this': '为什么？',
  'eat_this': '吃这个（{cals} 千卡）',

  // General
  'hello': '你好',
  'welcome': '欢迎',
  'logout': '登出',
  'settings': '设置',
  'profile': '个人资料',
  'about': '关于',
  'version': '版本',
  'language': '语言',
  'english': 'English',
  'arabic': 'العربية',
  'save': '保存',
  'cancel': '取消',
  'delete': '删除',
  'edit': '编辑',
  'add': '添加',
  'loading': '加载中',
  'error': '错误',
  'success': '成功',
  'try_again': '重试',

  // Health & Nutrition
  'calories': '卡路里',
  'protein': '蛋白质',
  'carbs': '碳水化合物',
  'fat': '脂肪',
  'water': '水',
  'hydration': '补水',
  'sleep_score': '睡眠评分',
  'heart_rate': '心率',
  'steps': '步数',
  'stress': '压力',
  'stress_level': '压力等级',

  // Meal & Food
  'meal': '餐',
  'meals': '餐',
  'breakfast': '早餐',
  'lunch': '午餐',
  'dinner': '晚餐',
  'snack': '零食',
  'log_meal': '记录餐食',
  'meal_suggestion': '餐食建议',
  'recipe': '食谱',
  'ingredients': '配料',
  'portion': '份量',
  'servings': '份',

  // Analytics & Time
  'analytics': '分析',
  'today': '今天',
  'week': '周',
  'month': '月',
  'year': '年',
  'daily': '每日',
  'weekly': '每周',
  'monthly': '每月',
  'history': '历史',
  'trend': '趋势',

  // Pantry & Planner
  'pantry': '储藏室',
  'planner': '计划器',
  'shopping': '购物',
  'leftover': '剩菜',
  'cooking_mode': '烹饪模式',
  'eating_out': '外出就餐',
};
