const Map<String, String> stringsRu = {
  // Dashboard & Navigation
  'bio_sync_active': 'Bio‑Sync активен',
  'hello_user': 'Привет, {name}',
  'new_suggestion_loaded': 'Загружено новое предложение',
  'coming_soon': 'Скоро',
  'finish_setup': 'Завершите настройку',
  'setup_description':
      'Заполните профиль, правила питания и синхронизацию устройств, чтобы разблокировать адаптивные планы.',
  'continue': 'Продолжить',
  'live_vitals': 'Показатели в реальном времени',
  'vitals_synced': 'Показатели синхронизированы',
  'ai_suggestion': 'Рекомендация ИИ',
  'daily_fuel': 'Ежедневная энергия',
  'quick_log': 'Быстрая запись',
  'view_history': 'Просмотр истории',
  'refresh': 'Обновить',
  'why_this': 'Почему это?',
  'eat_this': 'Съешьте это ({cals} ккал)',

  // General
  'hello': 'Привет',
  'welcome': 'Добро пожаловать',
  'logout': 'Выйти',
  'settings': 'Настройки',
  'profile': 'Профиль',
  'about': 'О приложении',
  'version': 'Версия',
  'language': 'Язык',
  'english': 'English',
  'arabic': 'العربية',
  'save': 'Сохранить',
  'cancel': 'Отмена',
  'delete': 'Удалить',
  'edit': 'Редактировать',
  'add': 'Добавить',
  'loading': 'Загрузка',
  'error': 'Ошибка',
  'success': 'Успех',
  'try_again': 'Попробовать снова',

  // Health & Nutrition
  'calories': 'Калории',
  'protein': 'Белки',
  'carbs': 'Углеводы',
  'fat': 'Жиры',
  'water': 'Вода',
  'hydration': 'Гидратация',
  'sleep_score': 'Оценка сна',
  'heart_rate': 'Частота сердечных сокращений',
  'steps': 'Шаги',
  'stress': 'Стресс',
  'stress_level': 'Уровень стресса',

  // Meal & Food
  'meal': 'Прием пищи',
  'meals': 'Приемы пищи',
  'breakfast': 'Завтрак',
  'lunch': 'Обед',
  'dinner': 'Ужин',
  'snack': 'Перекус',
  'log_meal': 'Записать прием пищи',
  'meal_suggestion': 'Рекомендация по еде',
  'recipe': 'Рецепт',
  'ingredients': 'Ингредиенты',
  'portion': 'Порция',
  'servings': 'Порции',

  // Analytics & Time
  'analytics': 'Аналитика',
  'today': 'Сегодня',
  'week': 'Неделя',
  'month': 'Месяц',
  'year': 'Год',
  'daily': 'Ежедневно',
  'weekly': 'Еженедельно',
  'monthly': 'Ежемесячно',
  'history': 'История',
  'trend': 'Тренд',

  // Pantry & Planner
  'pantry': 'Кладовая',
  'planner': 'Планировщик',
  'shopping': 'Покупки',
  'leftover': 'Остатки',
  'cooking_mode': 'Режим готовки',
  'eating_out': 'Еда вне дома',
};
