const Map<String, String> stringsEs = {
  'bio_sync_inactive': 'Bio-Sync Inactive',
  // Dashboard & Navigation
  'bio_sync_active': 'Bio-Sync activo',
  'hello_user': 'Hola, {name}',
  'new_suggestion_loaded': 'Nueva sugerencia cargada',
  'coming_soon': 'Próximamente',
  'finish_setup': 'Completa tu configuración',
  'setup_description':
      'Completa el perfil, reglas dietéticas y sincronización de dispositivos para desbloquear planes adaptativos.',
  'continue': 'Continuar',
  'live_vitals': 'Signos vitales en vivo',
  'vitals_synced': 'Signos vitales sincronizados',
  'ai_suggestion': 'Sugerencia IA',
  'daily_fuel': 'Energía diaria',
  'quick_log': 'Registro rápido',
  'view_history': 'Ver historial',
  'refresh': 'Actualizar',
  'why_this': '¿Por qué esto?',
  'eat_this': 'Come esto ({cals} kcal)',

  // General
  'hello': 'Hola',
  'welcome': 'Bienvenido',
  'logout': 'Cerrar sesión',
  'settings': 'Ajustes',
  'profile': 'Perfil',
  'about': 'Acerca de',
  'version': 'Versión',
  'language': 'Idioma',
  'english': 'English',
  'arabic': 'العربية',
  'save': 'Guardar',
  'cancel': 'Cancelar',
  'delete': 'Eliminar',
  'edit': 'Editar',
  'add': 'Agregar',
  'loading': 'Cargando',
  'error': 'Error',
  'success': 'Éxito',
  'try_again': 'Intentar de nuevo',

  // Health & Nutrition
  'calories': 'Calorías',
  'protein': 'Proteínas',
  'carbs': 'Carbohidratos',
  'fat': 'Grasas',
  'water': 'Agua',
  'hydration': 'Hidratación',
  'sleep_score': 'Puntuación de sueño',
  'heart_rate': 'Frecuencia cardíaca',
  'steps': 'Pasos',
  'stress': 'Estrés',
  'stress_level': 'Nivel de estrés',

  // Meal & Food
  'meal': 'Comida',
  'meals': 'Comidas',
  'breakfast': 'Desayuno',
  'lunch': 'Almuerzo',
  'dinner': 'Cena',
  'snack': 'Tentempié',
  'log_meal': 'Registrar comida',
  'meal_suggestion': 'Sugerencia de comida',
  'recipe': 'Receta',
  'ingredients': 'Ingredientes',
  'portion': 'Porción',
  'servings': 'Raciones',

  // Analytics & Time
  'analytics': 'Analíticas',
  'today': 'Hoy',
  'week': 'Semana',
  'month': 'Mes',
  'year': 'Año',
  'daily': 'Diario',
  'weekly': 'Semanal',
  'monthly': 'Mensual',
  'history': 'Historial',
  'trend': 'Tendencia',

  // Pantry & Planner
  'pantry': 'Despensa',
  'planner': 'Planificador',
  'shopping': 'Compras',
  'leftover': 'Sobras',
  'cooking_mode': 'Modo de cocina',
  'eating_out': 'Comer fuera',
};
